version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  server:
    build: ./server
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/recapp?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis

  client:
    build: ./client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  pgdata:
